# Generated by Django 5.1.3 on 2025-01-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0002_alter_orden_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='carnet',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='direccion',
        ),
        migrations.AddField(
            model_name='orden',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
