# Generated by Django 5.1.3 on 2025-02-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0003_remove_orden_carnet_remove_orden_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='tarjeta',
            field=models.CharField(max_length=19),
        ),
    ]
