# Generated by Django 5.1.3 on 2025-02-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0004_alter_orden_tarjeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorden',
            name='nombre_articulo',
        ),
        migrations.AddField(
            model_name='itemorden',
            name='producto_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
