# Generated by Django 5.1.3 on 2025-02-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0005_remove_itemorden_nombre_articulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorden',
            name='nombre_articulo',
            field=models.CharField(default='asd', max_length=100),
        ),
    ]
