# Generated by Django 5.1.3 on 2024-12-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anillo', '0003_rename_estado_anillo_es_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='anillo',
            name='unidades',
            field=models.IntegerField(default=0),
        ),
    ]
