# Generated by Django 5.1.3 on 2024-12-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anillo', '0004_anillo_unidades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anillo',
            old_name='unidades',
            new_name='cantUnidades',
        ),
    ]
