# Generated by Django 5.1.3 on 2025-01-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anillo', '0005_rename_unidades_anillo_cantunidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anillo',
            name='cantUnidades',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
