# Generated by Django 4.2.6 on 2024-11-12 03:32

import apps.Pircing.models
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pircing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('precio_unidad', models.FloatField(blank=True, default=0, null=True)),
                ('pureza', models.CharField(blank=True, default='0', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('size', models.CharField(blank=True, default='0', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('peso_neto', models.CharField(blank=True, default='0', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('estado', models.CharField(choices=[('privado', 'Privado'), ('publico', 'Publico')], default='privado', max_length=8)),
                ('genero_usuario', models.CharField(blank=True, choices=[('unisex', 'Unisex'), ('female', 'Female'), ('male', 'Male')], default='unisex', max_length=17, null=True)),
                ('lugar_de_uso', models.CharField(blank=True, choices=[('oreja', 'Oreja'), ('nariz', 'Nariz'), ('boca', 'Boca'), ('ombligo', 'Ombligo'), ('otro', 'Otro')], default='otro', max_length=7, null=True)),
                ('photo', models.ImageField(default='imgExample.jpg', upload_to=apps.Pircing.models.pircing_photo_directory)),
                ('photo2', models.ImageField(default='imgExample.jpg', upload_to=apps.Pircing.models.pircing_photo_directory)),
                ('photo3', models.ImageField(default='imgExample.jpg', upload_to=apps.Pircing.models.pircing_photo_directory)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
