# Generated by Django 5.1.3 on 2024-12-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pircing', '0004_pircing_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pircing',
            old_name='cantidad',
            new_name='unidades',
        ),
    ]
