# Generated by Django 5.1.3 on 2025-01-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pircing', '0006_rename_unidades_pircing_cantunidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pircing',
            name='cantUnidades',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
