# Generated by Django 5.1.3 on 2024-12-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadena', '0004_cadena_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadena',
            old_name='cantidad',
            new_name='unidades',
        ),
    ]
