# Generated by Django 5.1.3 on 2024-11-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arete',
            name='estado',
            field=models.BooleanField(default=False, max_length=8),
        ),
    ]
