# Generated by Django 5.1.3 on 2024-12-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arete', '0004_arete_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arete',
            name='cantidad',
        ),
    ]
