# Generated by Django 5.1.3 on 2024-12-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arete', '0005_remove_arete_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='arete',
            name='cantUnidades',
            field=models.IntegerField(default=0),
        ),
    ]
