# Generated by Django 5.1.3 on 2025-01-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arete', '0006_arete_cantunidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arete',
            name='cantUnidades',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
