# Generated by Django 5.1.3 on 2024-11-21 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tobillera', '0002_alter_tobillera_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tobillera',
            old_name='estado',
            new_name='es_publico',
        ),
    ]
