# Generated by Django 5.1.3 on 2024-12-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobillera', '0003_rename_estado_tobillera_es_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='tobillera',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
